version: '3'
services:
    nginx-ds:
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile
        volumes:
            - ${APPLICATION}:/var/www/html
            - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
            - ${NGINX_SITES_PATH}:/etc/nginx/conf.d
        ports:
            - "${NGINX_HOST_HTTP_PORT}:80"
            - "${NGINX_HOST_HTTPS_PORT}:443"
        links:
            - php-fpm
        networks:
            - network-ds

    php-fpm:
        restart: always
        build:
            context: ./php-fpm
            args:
                - INSTALL_GD=${PHP_FPM_INSTALL_GD}
                - INSTALL_COMPRESSION=${PHP_FPM_INSTALL_COMPRESSION}
                - INSTALL_FTP=${PHP_FPM_INSTALL_FTP}
                - INSTALL_MBSTRING=${PHP_FPM_INSTALL_MBSTRING}
                - INSTALL_MCRYPT=${PHP_FPM_INSTALL_MCRYPT}
                - INSTALL_PDO_MYSQL=${PHP_FPM_INSTALL_PDO_MYSQL}
                - INSTALL_PDO_POSTGRESQL=${PHP_FPM_INSTALL_PDO_POSTGRESQL}
                - INSTALL_MYSQLI=${PHP_FPM_INSTALL_MYSQLI}
                - INSTALL_BCMATH=${PHP_FPM_INSTALL_BCMATH}
                - INSTALL_OPCACHE=${PHP_FPM_INSTALL_OPCACHE}
                - INSTALL_INTL=${PHP_FPM_INSTALL_INTL}
                - INSTALL_XDEBUG=${PHP_FPM_INSTALL_XDEBUG}
                - INSTALL_TOKENIZER=${PHP_FPM_INSTALL_TOKENIZER}
                - INSTALL_JSON_XML=${PHP_FPM_INSTALL_JSON_XML}
                - INSTALL_CURL=${PHP_FPM_INSTALL_CURL}
                - INSTALL_OPENSSL=${PHP_FPM_INSTALL_OPENSSL}
                - INSTALL_COMPOSER=${PHP_FPM_INSTALL_COMPOSER}
            dockerfile: Dockerfile
        expose:
            - "9000"
        volumes:
            - ${APPLICATION}:/var/www/html
        depends_on:
            - postgres-ds
        networks:
            - network-ds

    postgres-ds:
        restart: always
        build:
            context: ./postgresql
            dockerfile: Dockerfile
        ports:
            - "${POSTGRES_PORT}:5432"
        volumes:
            - post-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        networks:
            - network-ds
    pgadmin-ds:
        restart: always
        image: dpage/pgadmin4:latest
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASS}
        ports:
            - "${PGADMIN_PORT}:80"
        depends_on:
            - postgres-ds
        networks:
            - network-ds
volumes:
    post-data:
networks:
    network-ds:
        driver: bridge